### ISSUE TITLE
Docker install error

### ISSUE THREAD

**Issue by tehniemer** [NotCompsky/tagem#3]
I'm having a problem getting this container up and running, this is the error I'm getting
```/tagem-server: error while loading shared libraries: libffmpegthumbnailer.so.4: cannot open shared object file: No such file or directory```

Here is the relevant snippet of my compose file.
```
version: "3.3"

networks:
  proxy:
    external:
      name: proxy
  tagem:
    driver: bridge

## MariaDB - MySQL Database
  tagemdb:
    image: linuxserver/mariadb:latest
    container_name: tagemdb
    restart: always
    networks:
      - tagem
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CONFIG_DIR/tagem/db:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      PUID: $PUID
      PGID: $PGID
      MYSQL_ROOT_PASSWORD: $ROOT_PASS
      MYSQL_DATABASE: db
      MYSQL_USER: tagem
      MYSQL_PASSWORD: $USER_PASS
      MYSQL_ROOT_HOST: "%"

# Tagem - A single page application, with associated command-line utilities, for the rapid categorising and accessing of files, based on assignable attributes such as (heirarchical) tags, named variables, file sizes, hashes, and audio duration.
# Create all databases and files first
  tagem:
    image: notcompsky/tagem:latest
    container_name: tagem
    restart: always
    networks:
      - proxy
      - tagem
    volumes:
      - $CONFIG_DIR/tagem/tagem-auth.cfg:/tagem-auth.cfg
      - /etc/localtime:/etc/localtime:ro
    security_opt:
      - no-new-privileges:true
    ports:
      - "$TAGEM_PORT:80"
    depends_on:
     - tagemdb
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.tagem-rtr.entrypoints=https"
      - "traefik.http.routers.tagem-rtr.rule=Host(`tagem.$DOMAIN_NAME`)"
      - "traefik.http.routers.tagem-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.tagem-rtr.middlewares=chain-oauth@file,add-tagem" # Google OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.tagem-rtr.service=tagem-svc"
      - "traefik.http.services.tagem-svc.loadbalancer.server.port=80"
```

**Comment by NotCompsky** [comment]
Okay, it appears I made quite a silly mistake - I forgot to commit a line in the Dockerfile installing the `ffmpegthumbnailer` package.

I've pushed it now, the updated DockerHub image should be available in a few minutes - please let me know if it fixes the issue!

**Comment by NotCompsky** [comment]
Okay, it appears I made quite a silly mistake - I forgot to commit a line in the Dockerfile installing the `ffmpegthumbnailer` package, and tested a local Docker build rather than the DockerHub build.

The fix will come out shortly, I've just noticed another thing I need to patch.

**Comment by tehniemer** [comment]
That helped me get a little further, now, after creating the .cfg file I get the following error

```
terminate called after throwing an instance of 'compsky::mysql::except::FileOpen'
  what():  Error opening file: /opt/docker/tagem/tagem-auth.cfg
*** Aborted at 1595940469 (unix time) try "date -d @1595940469" if you are using GNU date ***
PC: @     0x7f687bd7318b gsignal
*** SIGABRT (@0x7) received by PID 7 (TID 0x7f6870379600) from PID 7; stack trace: ***
    @     0x7f687c32b631 (unknown)
    @     0x7f687c2643c0 (unknown)
    @     0x7f687bd7318b gsignal
    @     0x7f687bd52859 abort
    @     0x7f687c10c951 (unknown)
    @     0x7f687c11847c (unknown)
    @     0x7f687c1184e7 std::terminate()
    @     0x7f687c118799 __cxa_throw
    @     0x55ee680ba8cb (unknown)
    @     0x55ee6808b59d (unknown)
    @     0x7f687bd540b3 __libc_start_main
    @     0x55ee6808cdbe (unknown)
Aborted (core dumped)
```

my compose file (networks and database did not change from first post)
```
## Tagem - A single page application, with associated command-line utilities, for the rapid categorising and accessing of files, based on assignable attributes such as (heirarchical) tags, named variables, file sizes, hashes, and audio duration.
# Create all databases and files first
  tagem:
    image: notcompsky/tagem:latest
    container_name: tagem
    restart: always
    networks:
      - proxy
      - tagem
    volumes:
      - $CONFIG_DIR/tagem/tagem-auth.cfg:/tagem-auth.cfg
      - /etc/localtime:/etc/localtime:ro
    security_opt:
      - no-new-privileges:true
    ports:
      - "$TAGEM_PORT:80"
    environment:
      TAGEM_MYSQL_CFG: $CONFIG_DIR/tagem/tagem-auth.cfg
    depends_on:
     - tagemdb
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.tagem-rtr.entrypoints=https"
      - "traefik.http.routers.tagem-rtr.rule=Host(`tagem.$DOMAIN_NAME`)"
      - "traefik.http.routers.tagem-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.tagem-rtr.middlewares=chain-oauth@file,add-tagem" # Google OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.tagem-rtr.service=tagem-svc"
      - "traefik.http.services.tagem-svc.loadbalancer.server.port=80"
```

my tagem-auth.cfg
```
HOST: tagemdb
PATH: /
USER: tagem
PWRD: supersecretpw
DBNM: db
PORT: 3306
DONT DELETE THIS LINE MMKAY
```
